### ISSUE TITLE
java.lang.NoClassDefFoundError: openvr/EVREye

### ISSUE THREAD

**Issue by lisphacker** [jovr/jogl-hello-vr#3]
Hi

(Sorry for the x-post)

I've been trying to get this project running under Windows. I was able to build the application after adding the Kotlin compilers and Eclipse kotlin support. However, when I try to run the project, I get the exception 'java.lang.NoClassDefFoundError: openvr/EVREye'

I'm using the following batch file to run the program:

```
@echo off

set CLASSPATH=build\libs\jogl-hello-vr.jar;jogl-hello-vr\lib\gluegen-rt.jar;jogl-hello-vr\lib\jogl-all.jar;jogl-hello-vr\lib\openvr.jar;jogl-hello-vr\lib\glm.jar;jogl-hello-vr\lib\jna-4.2.2.jar;jogl-hello-vr\lib\streamex-0.6.2-SNAPSHOT.jar

kotlin -classpath %CLASSPATH% hellovr.App
```

Can you see any mistakes in what I am doing? Any help in getting this running would be much appreciated.

Cheers

**Comment by xinaesthete** [comment]
I must admit I seem to remember when I got this working before I may have had some hacky patching possibly even inside the source somewhere to get it to find the native library properly, hopefully someone else'll weigh in, but I might try to look back at it for you.

It might be as simple as you needing to add a `-Djava.library.path` argument.  It's been a little while since I've done any Java (never even glanced at kotlin) and I'm a little foggy on remembering how this project dealt with its native dependencies but I remember it needing a little bit of hacking to work for me in Eclipse.

**Comment by elect86** [comment]
Could you try with Idea?

**Comment by lisphacker** [comment]
Cheers guys. I think I see the class file in the openvr jar, just not able to get the JVM to pick it up. I'll fiddle around with the class paths a bit more as you suggested and see if I can get it working.

I'll try out Idea too.

**Comment by lisphacker** [comment]
Gradle was downloading jar files for openvr, glm and uno-sdk from maven repos synced with the @elect86's github account and compiling against them, and it looks like these did not match the files in the libs directory (which I was trying to run against). I made some progress after using the jar files downloaded by gradle, but after trying out Idea as suggested by @elect86, it just worked!

If I get some time, I might try an update the example to work with the updated libs and submit a merge request.

Cheers!

**Comment by elect86** [comment]
Nice to hear it worked

Pull requests are welcome :)
